[DPE-3929] - feat: secrets integration
canonical/kafka-k8s-operator pull request #105
Opened 2024-04-28 02:24 UTC by marcoppenheimer

Majority of changes are synced from https://github.com/canonical/kafka-operator/pull/189. See that PR for features, refactoring and bug-fixes

2024-05-02 10:42 UTC, deusebio approved these changes
Following discussions and approval on https://github.com/canonical/kafka-operator/pull/189

2024-05-02 15:40 UTC, Batalex requested changes
Like you said, a lot of test tweaking!

2024-05-02 18:53 UTC, Batalex commented on tests/integration/app-charm/src/charm.py
> +            uris = relation.data[relation.app].get("endpoints", "").split(",")
Yup, all good

2024-05-03 07:27 UTC, Batalex approved these changes

2024-05-03 08:36 UTC, zmraul approved these changes

2024-05-03 14:10 UTC, merged