Add data_interfaces
canonical/kafka-k8s-operator pull request #29
Opened 2023-01-18 16:08 UTC by welpaolo

This PR adds the data_interfaces library in the Kafka K8s charm.

2023-01-18 17:05 UTC, marcoppenheimer requested changes
Left some minor comments and nitpicks, but overall I think this is really solid and a massive improvement on the code quality of the charm. 

Really happy you chose to tidy up bits beyond the scope of the ticket, it's made a big difference.

2023-01-18 17:05 UTC, marcoppenheimer commented on tests/integration/test_provider.py
> +    # HERE
**nitpick:** Comments can be removed I think.

2023-01-18 17:05 UTC, marcoppenheimer commented on tests/integration/test_provider.py
> +    # )
**nitpick:** Comments can be removed here.

2023-01-18 17:05 UTC, marcoppenheimer commented on tests/integration/test_provider.py
> +    # await ops_test.model.deploy(app_charm, application_name=DUMMY_NAME_1, num_units=1),
**nitpick:** Same here.

2023-01-19 08:50 UTC, deusebio commented on src/provider.py
> +        return self.charm.model.get_relation(PEER)
I guess this is only reshuffling position of a method that was already there, but a bit further up in the file. I'm not sure what your point @marcoppenheimer

2023-01-19 09:17 UTC, deusebio submitted a review, later dismissed
Very good work @welpaolo !

2023-01-19 11:43 UTC, welpaolo commented on tests/integration/test_charm.py
> +    await ops_test.model.add_relation(APP_NAME, f"{DUMMY_NAME}:{REL_NAME_ADMIN}")
Yes this is right!

2023-01-20 13:38 UTC, marcoppenheimer approved these changes
Ayy tests pass, nice job! LGTM

2023-01-20 13:46 UTC, deusebio approved these changes
All good!

2023-01-20 13:46 UTC, merged