Improve readme
canonical/kafka-k8s-operator pull request #32
Opened 2023-01-27 10:55 UTC by zmraul

Addresses [DPE-1010](https://warthogs.atlassian.net/browse/DPE-1010).

Change docs to follow current readme scheme.

2023-01-27 12:18 UTC, deusebio requested changes
Great work @zmraul !! Looks that this docs is really shaping up!!!!

Just few points before approving:

1. As pointed out in the comments, there are some misalingment between documentation and charm features (just make sure that the commands we put here they do work with a dry run)
2. I believe we need to give some love to the metadata too. Description and summary are missing there, and make sure we put the right info for the other fields
3. I believe it would be good to also put some texts about storage handling in the usage as we have this feature in (marc can maybe help if you are unsure)
4. I believe it would be good to also put some texts about the data-integrator (paolo can maybe help if you are unsure)

2023-01-27 12:18 UTC, deusebio commented on README.md
> +juju run-action kafka-k8s/2 set-tls-private-key "external-key=$(base64 -w0 external-key-2.pem)"  "internal-key=$(base64 -w0 internal-key.pem)"  --wait
I'm not sure we have the `external-key` option in that action. I believe we have to adapt the Config section as well

2023-01-30 07:19 UTC, welpaolo approved these changes
Great improvement! I left a small comment

2023-01-30 07:19 UTC, welpaolo commented on README.md
> +#### `data-integrator` interface:
I think the interface name should be kafka-client. This interface is implemented in the data-integrator.
Suggestion: maybe you can copy/paste two sentences to add a description for the data-integrator

2023-01-30 11:08 UTC, deusebio approved these changes
Looks good!

2023-01-30 18:26 UTC, welpaolo approved these changes
Great work!

2023-01-31 09:35 UTC, merged