chore: add DEPENDENCIES
canonical/kafka-k8s-operator pull request #79
Opened 2024-01-22 15:49 UTC by marcoppenheimer

## Changes Made
#### `feat: add in-place upgrade support`
- Disabled the `resume-upgrade` functionality from the lib, to keep behavior the same between VM + K8s
- Although it works, upgrades on K8s needs to be manually tested more thoroughly before merging. NOTE - int test is skipped for now, as we don't have a published `stable` charm to test against
- No unit-tests right now, as they're currently being refactored

2024-01-26 14:13 UTC, zmraul requested changes
Nice! Sorry for blocking with the refactor here. I left some comments. There is one piece that is missing from the PR, see comment about `inter.broker.protocol.version`

2024-01-26 14:13 UTC, zmraul commented on src/events/upgrade.py
> +    def _on_kafka_pebble_ready_upgrade(self, event: EventBase) -> None:
**question:** Why can't this hook follow the same pattern as vm? I mainly mean the call to `self.charm._on_update_status(event)` If that call is needed then my other comment about update_status check can be ignored.

2024-01-26 14:13 UTC, zmraul commented on src/events/upgrade.py
> +    def idle(self) -> bool:
This is different than vm. Should we change it back there?

2024-01-26 14:13 UTC, zmraul commented on src/events/upgrade.py
> -        return dependency_model.version
**todo:** This property needs to be used. The upgrade is missing the `inter.broker.protocol.version` addition to `server.properties`. [See here](https://github.com/canonical/kafka-operator/pull/127/files#diff-24a3fe5c783755412cb9de83238b4dfd0699345bf50dcadc3ec23c6749361592R456-R465)

2024-01-26 14:15 UTC, marcoppenheimer commented
> Sorry for blocking with the refactor here

No worries! Was just getting it out early for review, helpful comments :). I'll address these next week.

2024-02-01 11:19 UTC, zmraul requested changes
Related to the `inter.broker.protocol.version` field:
```
$ diff -C 10 src/managers/config.py ../kafka-operator/src/managers/config.py 
*** src/managers/config.py      2024-01-29 17:36:01.183034389 +0100
--- ../kafka-operator/src/managers/config.py    2024-01-29 17:43:14.819713568 +0100
***************
*** 97,120 ****
--- 97,122 ----
  
  
  class KafkaConfigManager:
      """Manager for handling Kafka configuration."""
  
      def __init__(
          self,
          state: ClusterState,
          workload: WorkloadBase,
          config: CharmConfig,
+         current_version: str,
      ):
          self.state = state
          self.workload = workload
          self.config = config
+         self.current_version = current_version
  
      @property
      def log_level(self) -> str:
          """Return the Java-compliant logging level set by the user.
  
          Returns:
              String with these possible values: DEBUG, INFO, WARN, ERROR
          """
          # Remapping to WARN that is generally used in Java applications based on log4j and logback.
          if self.config.log_level == LogLevel.WARNING.value:
***************
*** 305,324 ****
--- 307,337 ----
              Listener(host=self.state.broker.host, protocol=auth, scope="CLIENT")
              for auth in self.auth_mechanisms
          ]
  
      @property
      def all_listeners(self) -> list[Listener]:
          """Return a list with all expected listeners."""
          return [self.internal_listener] + self.client_listeners
  
      @property
+     def inter_broker_protocol_version(self) -> str:
+         """Creates the protocol version from the kafka version.
+ 
+         Returns:
+             String with the `major.minor` version
+         """
+         # Remove patch number from full vervion.
+         major_minor = self.current_version.split(".", maxsplit=2)
+         return ".".join(major_minor[:2])
+ 
+     @property
      def rack_properties(self) -> list[str]:
          """Builds all properties related to rack awareness configuration.
  
          Returns:
              List of properties to be set
          """
          # TODO: not sure if we should make this an instance attribute like the other paths
          rack_path = f"{self.workload.paths.conf_path}/rack.properties"
          return self.workload.read(rack_path) or []
  
***************
*** 364,383 ****
--- 377,397 ----
          advertised_listeners = [listener.advertised_listener for listener in self.all_listeners]
  
          properties = (
              [
                  f"super.users={self.state.super_users}",
                  f"log.dirs={self.state.log_dirs}",
                  f"listener.security.protocol.map={','.join(protocol_map)}",
                  f"listeners={','.join(listeners_repr)}",
                  f"advertised.listeners={','.join(advertised_listeners)}",
                  f"inter.broker.listener.name={self.internal_listener.name}",
+                 f"inter.broker.protocol.version={self.inter_broker_protocol_version}",
              ]
              + self.config_properties
              + self.scram_properties
              + self.default_replication_properties
              + self.auth_properties
              + self.rack_properties
              + DEFAULT_CONFIG_OPTIONS.split("\n")
          )
  
          if self.state.cluster.tls_enabled and self.state.broker.certificate:
```

2024-02-02 12:58 UTC, zmraul approved these changes

2024-02-02 14:59 UTC, merged